apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calrissian-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage}}
  storageClassName: {{ .Values.pvc.storageClassName}}